"""
Django settings for school_website project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
# Keep your current SECRET_KEY value here (do NOT change it unless you know why).
SECRET_KEY = "REPLACE_WITH_YOUR_EXISTING_SECRET_KEY"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # set to False when going live

# Hosts / domains that are valid for this site
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "63.250.47.196",
    "jananluwummemorialsss.sc.ug",
    "www.jananluwummemorialsss.sc.ug",
    "admission.jananluwummemorialsss.sc.ug",
]

# If you temporarily need to allow everything for debugging ONLY:
# ALLOWED_HOSTS = ["*"]

# Application definition
INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "ckeditor",
    "ckeditor_uploader",

    "school",
    "admissions.apps.AdmissionsConfig",
    "helpdesk.apps.HelpdeskConfig",
]

MIDDLEWARE = [
    "admissions.middleware.AdmissionSubdomainMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "school_website.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",

                # Your extras
                "django.template.context_processors.media",
                "school.context_processors.school_info",
                "admissions.context_processors.admission_context",
            ],
        },
    },
]

WSGI_APPLICATION = "school_website.wsgi.application"

# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Africa/Kampala"
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# You currently have both static/ and "raw media" as static dirs. Keep them:
STATICFILES_DIRS = [
    BASE_DIR / "static",
    BASE_DIR / "raw media",
]

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# CKEditor settings
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    "default": {
        "toolbar": "full",
        "height": 300,
        "width": "100%",
    }
}

# If you use ckeditor uploader URLs, ensure you included it in urls.py too.

# Proxy / Cloudflare / Nginx settings
# This makes Django correctly understand HTTPS when Cloudflare is in front.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

# When you switch to HTTPS on Cloudflare, set this to True (recommended):
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Jazzmin settings (kept as you had them)
JAZZMIN_SETTINGS = {
    "site_title": "Janan Luwum Memorial Admin",
    "site_header": "JLMSSS Administrative Dashboard",
    "site_brand": "JLMSSS Control Center",
    "welcome_sign": "Welcome to Janan Luwum Memorial Senior Secondary School",
    "site_icon": "img/school-badge.png",
    "site_logo": "img/school-badge.png",
    "login_logo": "img/school-badge.png",
    "site_logo_classes": "img-circle elevation-3",
    "custom_css": "css/jazzmin-custom.css",
    "custom_js": "js/jazzmin-custom.js",
    "show_ui_builder": False,

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user-shield",
        "auth.group": "fas fa-user-tag",

        "school.schoolinfo": "fas fa-school",
        "school.websiteconfig": "fas fa-sliders-h",
        "school.page": "fas fa-file-alt",
        "school.news": "fas fa-newspaper",
        "school.newscategory": "fas fa-tags",
        "school.announcement": "fas fa-bullhorn",
        "school.event": "fas fa-calendar-alt",
        "school.gallery": "fas fa-images",
        "school.gallerycategory": "fas fa-folder-open",
        "school.headteachermessage": "fas fa-video",
        "school.contactmessage": "fas fa-envelope",

        "school.staff": "fas fa-chalkboard-teacher",
        "school.department": "fas fa-building",
        "school.studentleader": "fas fa-user-graduate",
        "school.admissiondocument": "fas fa-file-signature",
        "school.academicperformance": "fas fa-chart-line",

        "admissions.admissionwindow": "fas fa-window-maximize",
        "admissions.application": "fas fa-file-signature",
        "admissions.admissionform": "fas fa-wpforms",
        "helpdesk.helpsession": "fas fa-comments",
    },

    "order_with_respect_to": [
        "school",
        "school.schoolinfo",
        "school.websiteconfig",
        "school.page",
        "school.news",
        "school.newscategory",
        "school.announcement",
        "school.event",
        "school.gallery",
        "school.gallerycategory",
        "school.headteachermessage",
        "school.staff",
        "school.department",
        "school.studentleader",
        "school.admissiondocument",
        "school.academicperformance",
        "school.contactmessage",
        "admissions",
        "admissions.admissionwindow",
        "admissions.admissionform",
        "admissions.application",
        "helpdesk",
        "helpdesk.helpsession",
        "auth",
        "auth.user",
        "auth.group",
    ],

    "topmenu_links": [
        {"name": "Change password", "url": "admin:password_change"},
    ],

    "usermenu_links": [
        {"name": "Change password", "url": "admin:password_change"},
    ],
}

JAZZMIN_UI_TWEAKS = {
    "theme": "lumen",
    "dark_mode_theme": None,
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "sidebar": "sidebar-dark-success",
    "sidebar_fixed": True,
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "accent": "accent-success",
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "footer_small_text": False,
    "actions_sticky_top": True,
}

# ============================================================
# EMAIL (Gmail SMTP - App Password)
# ============================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'jananluwummemorialsss@gmail.com'
EMAIL_HOST_PASSWORD = 'ypvw mluh blhj suit'
DEFAULT_FROM_EMAIL = 'JLMSSS Admissions <jananluwummemorialsss@gmail.com>'
SERVER_EMAIL = 'jananluwummemorialsss@gmail.com'

# ============================================================
# ADMISSION SUBDOMAIN
# ============================================================
ADMISSION_EMAIL_FROM = 'JLMSSS Admissions <jananluwummemorialsss@gmail.com>'
ADMIN_NOTIFICATION_EMAIL = 'jananluwummemorialsss@gmail.com'
ADMISSION_SUBDOMAIN_HOST = 'admission.jananluwummemorialsss.sc.ug'
ADMISSION_SUBDOMAIN = 'https://admission.jananluwummemorialsss.sc.ug'
