# Generated by Django 5.2.8 on 2025-11-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headteachermessage',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Administrator Video Message', 'verbose_name_plural': 'Administrator Video Messages'},
        ),
        migrations.AddField(
            model_name='headteachermessage',
            name='admin_name',
            field=models.CharField(blank=True, help_text='Name of the administrator (optional)', max_length=200),
        ),
        migrations.AddField(
            model_name='headteachermessage',
            name='admin_type',
            field=models.CharField(choices=[('headteacher', 'Headteacher'), ('deputy', 'Deputy Headteacher'), ('principal', 'Principal'), ('director', 'Director'), ('other', 'Other Administrator')], default='headteacher', help_text='Type of administrator', max_length=50),
        ),
        migrations.AddField(
            model_name='headteachermessage',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
    ]
