# Generated by Django 5.2.8 on 2025-11-24 00:02

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_websiteconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., "S.4 Results 2024" or "First Term 2024"', max_length=200)),
                ('year', models.CharField(choices=[('2024', '2024'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020')], max_length=4)),
                ('term', models.CharField(blank=True, choices=[('term1', 'First Term'), ('term2', 'Second Term'), ('term3', 'Third Term'), ('annual', 'Annual')], help_text='Leave blank for annual results', max_length=10)),
                ('level', models.CharField(choices=[('s4', 'Senior 4 (UCE)'), ('s6', 'Senior 6 (UACE)'), ('other', 'Other')], default='other', max_length=10)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('document', models.FileField(blank=True, help_text='PDF or document with detailed results', null=True, upload_to='academics/performance/')),
                ('summary', models.TextField(blank=True, help_text='Brief summary of performance')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Performance',
                'verbose_name_plural': 'Academic Performance Records',
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('form', 'Admission Form'), ('requirements', 'Requirements'), ('guidelines', 'Guidelines'), ('fee_structure', 'Fee Structure'), ('other', 'Other')], default='form', max_length=50)),
                ('file', models.FileField(upload_to='admission/documents/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admission Document',
                'verbose_name_plural': 'Admission Documents',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gallery Category',
                'verbose_name_plural': 'Gallery Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3b82f6', help_text='Hex color code for category badge', max_length=7)),
            ],
            options={
                'verbose_name': 'News Category',
                'verbose_name_plural': 'News Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('head_prefect', 'Head Prefect'), ('deputy_prefect', 'Deputy Prefect'), ('academic_prefect', 'Academic Prefect'), ('sports_prefect', 'Sports Prefect'), ('entertainment_prefect', 'Entertainment Prefect'), ('health_prefect', 'Health Prefect'), ('library_prefect', 'Library Prefect'), ('dormitory_prefect', 'Dormitory Prefect'), ('class_representative', 'Class Representative'), ('other', 'Other')], max_length=50)),
                ('class_level', models.CharField(blank=True, help_text='e.g., S.4, S.5, S.6', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_leaders/')),
                ('bio', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Student Leader',
                'verbose_name_plural': 'Student Leaders',
                'ordering': ['order', 'position', 'last_name'],
            },
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=200),
        ),
        migrations.AddField(
            model_name='staff',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='All departments this staff member teaches (can select multiple)', related_name='staff_members', to='school.department'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Primary department', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.department'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='school.gallerycategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.newscategory'),
        ),
    ]
