# Generated by Django 5.2.8 on 2026-07-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_ensure_student_life_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(help_text='Upload the MP4 video file', upload_to='activities/')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Activity Video',
                'verbose_name_plural': 'Activity Videos',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
