# Generated by Django 6.1.1 on 2026-09-22 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationfile',
            options={'verbose_name': 'Application File (Legacy)', 'verbose_name_plural': 'Application Files (Legacy)'},
        ),
        migrations.AlterModelOptions(
            name='applicationstatuslog',
            options={'ordering': ['changed_at'], 'verbose_name': 'Status Log Entry', 'verbose_name_plural': 'Status Log'},
        ),
        migrations.AlterModelOptions(
            name='fieldoption',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='accepted_file_types',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='help_text_luganda',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='help_text_runyakore',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='max_file_size_mb',
        ),
        migrations.AddField(
            model_name='admissionwindow',
            name='offer_letter_intro',
            field=models.TextField(blank=True, help_text='Opening paragraph for auto-generated offer letters for this window.', verbose_name='Offer Letter Introduction'),
        ),
        migrations.AddField(
            model_name='admissionwindow',
            name='resubmission_deadline_days',
            field=models.IntegerField(default=7, help_text='Days given to applicants to correct flagged documents.', verbose_name='Resubmission Deadline (days)'),
        ),
        migrations.AddField(
            model_name='applicantaccount',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email Verified'),
        ),
        migrations.AddField(
            model_name='applicantaccount',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='admissions/profile_photos/'),
        ),
        migrations.AddField(
            model_name='applicantaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Offer Accepted At'),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_accepted_by_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_letter',
            field=models.FileField(blank=True, null=True, upload_to='admissions/offer_letters/', verbose_name='Offer Letter PDF'),
        ),
        migrations.AddField(
            model_name='application',
            name='resubmission_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Resubmission Deadline'),
        ),
        migrations.AddField(
            model_name='application',
            name='resubmission_notes',
            field=models.TextField(blank=True, verbose_name='Resubmission Instructions'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='icon',
            field=models.CharField(blank=True, default='fas fa-list', max_length=60),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='entry_class',
            field=models.CharField(choices=[('s1', 'Senior 1'), ('s2', 'Senior 2'), ('s3', 'Senior 3'), ('s4', 'Senior 4'), ('s5', 'Senior 5'), ('s6', 'Senior 6')], max_length=5),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='admissions.admissionwindow'),
        ),
        migrations.AlterField(
            model_name='admissionwindow',
            name='eligibility_rules',
            field=models.TextField(blank=True, verbose_name='Eligibility Rules'),
        ),
        migrations.AlterField(
            model_name='admissionwindow',
            name='interview_details',
            field=models.TextField(blank=True, verbose_name='Interview Details'),
        ),
        migrations.AlterField(
            model_name='admissionwindow',
            name='max_total_students',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Total Students'),
        ),
        migrations.AlterField(
            model_name='applicantaccount',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicantaccount',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='applicantaccount',
            name='nationality',
            field=models.CharField(blank=True, default='Ugandan', max_length=100),
        ),
        migrations.AlterField(
            model_name='applicantaccount',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('lg', 'Luganda'), ('rk', 'Runyakore-Rukiga')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='applicantaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='admissions.applicantaccount', verbose_name='Account Holder'),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Rejection Reason'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_doc_review', 'Under Document Review'), ('action_required', 'Action Required / Resubmission Needed'), ('docs_resubmitted', 'Documents Resubmitted'), ('approved', 'Approved'), ('provisionally_admitted', 'Provisionally Admitted'), ('enrolled', 'Enrolled'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='admissions.admissionwindow'),
        ),
        migrations.AlterField(
            model_name='applicationfile',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='admissions.application'),
        ),
        migrations.AlterField(
            model_name='applicationfile',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.formfield'),
        ),
        migrations.AlterField(
            model_name='applicationfile',
            name='field_key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='applicationfile',
            name='file',
            field=models.FileField(upload_to='admissions/files/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='applicationfile',
            name='file_size_kb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='applicationfile',
            name='original_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='applicationresponse',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='admissions.application'),
        ),
        migrations.AlterField(
            model_name='applicationresponse',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.formfield'),
        ),
        migrations.AlterField(
            model_name='applicationresponse',
            name='field_key',
            field=models.CharField(max_length=100, verbose_name='Field Key (Snapshot)'),
        ),
        migrations.AlterField(
            model_name='applicationresponse',
            name='text_value',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='applicationstatuslog',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='admissions.application'),
        ),
        migrations.AlterField(
            model_name='applicationstatuslog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationstatuslog',
            name='from_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='applicationstatuslog',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='applicationstatuslog',
            name='to_status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='fieldoption',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='admissions.formfield'),
        ),
        migrations.AlterField(
            model_name='fieldoption',
            name='label',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fieldoption',
            name='label_luganda',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fieldoption',
            name='label_runyakore',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fieldoption',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fieldoption',
            name='value',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='condition_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_fields', to='admissions.formfield'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='condition_operator',
            field=models.CharField(blank=True, choices=[('eq', 'Equals'), ('neq', 'Not Equals'), ('contains', 'Contains')], max_length=20),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='condition_value',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_key',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('email', 'Email Address'), ('phone', 'Phone Number'), ('number', 'Number'), ('date', 'Date'), ('select', 'Dropdown'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkboxes'), ('heading', 'Section Heading'), ('paragraph', 'Informational Paragraph')], max_length=20),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='help_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='label_luganda',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='label_runyakore',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='placeholder',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='admissions.formsection'),
        ),
        migrations.AlterField(
            model_name='formsection',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='formsection',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='admissions.admissionform'),
        ),
        migrations.AlterField(
            model_name='formsection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='formsection',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formsection',
            name='title_luganda',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='formsection',
            name='title_runyakore',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='interview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='admissions.application'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='duration_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interviewer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='interview',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='interview',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='outcome',
            field=models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='interview',
            name='outcome_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='scheduled_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='paymentconfig',
            name='additional_instructions',
            field=models.TextField(blank=True, verbose_name='Additional Payment Instructions'),
        ),
        migrations.AlterField(
            model_name='transferinfo',
            name='any_disciplinary_issues',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transferinfo',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_info', to='admissions.application'),
        ),
        migrations.AlterField(
            model_name='transferinfo',
            name='date_last_attended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferinfo',
            name='disciplinary_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transferinfo',
            name='headteacher_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='transferinfo',
            name='outstanding_fees',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferinfo',
            name='previous_school_contact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transferinfo',
            name='previous_school_district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transferinfo',
            name='previous_school_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transferinfo',
            name='reason_for_leaving',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transferinfo',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transferinfo',
            name='verification_token',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='transferinfo',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferinfo',
            name='verified_by_school',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='windowentryclass',
            name='intake_type',
            field=models.CharField(choices=[('new', 'New Entrant'), ('transfer', 'Transfer Student'), ('both', 'New & Transfer')], default='both', max_length=10),
        ),
        migrations.AlterField(
            model_name='windowentryclass',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='Open for Applications'),
        ),
        migrations.AlterField(
            model_name='windowentryclass',
            name='max_students',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vacancies'),
        ),
        migrations.AlterField(
            model_name='windowentryclass',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='windowentryclass',
            name='window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_classes', to='admissions.admissionwindow'),
        ),
        migrations.CreateModel(
            name='AdminFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('action_required', 'Action Required'), ('general_info', 'General Information'), ('rejection_notice', 'Rejection Notice'), ('congratulations', 'Congratulations / Offer')], default='action_required', max_length=30)),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message to Applicant')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Email Sent')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='admissions.application')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Feedback',
                'verbose_name_plural': 'Admin Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='Action Performed')),
                ('details', models.TextField(blank=True, verbose_name='Additional Details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='admissions.application')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Document Name')),
                ('slot_key', models.SlugField(max_length=100, verbose_name='Slot Key')),
                ('description', models.TextField(blank=True, verbose_name='Description / Instructions')),
                ('is_required', models.BooleanField(default=True, verbose_name='Required')),
                ('accepted_types', models.CharField(default='pdf,jpg,jpeg,png', help_text='Comma-separated, e.g. pdf,jpg,png', max_length=100, verbose_name='Accepted File Types')),
                ('max_size_mb', models.IntegerField(default=5, verbose_name='Max File Size (MB)')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('icon', models.CharField(default='fas fa-file-alt', max_length=50, verbose_name='Icon (Font Awesome class)')),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_slots', to='admissions.admissionwindow', verbose_name='Admission Window')),
            ],
            options={
                'verbose_name': 'Document Slot',
                'verbose_name_plural': 'Document Slots',
                'ordering': ['order', 'name'],
                'unique_together': {('window', 'slot_key')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_key', models.CharField(max_length=100, verbose_name='Slot Key (Snapshot)')),
                ('slot_name', models.CharField(max_length=200, verbose_name='Slot Name (Snapshot)')),
                ('file', models.FileField(upload_to='admissions/documents/%Y/%m/', verbose_name='Uploaded File')),
                ('original_name', models.CharField(max_length=255, verbose_name='Original File Name')),
                ('file_size_kb', models.IntegerField(default=0, verbose_name='File Size (KB)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME Type')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('flagged', 'Flagged / Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin Note / Feedback on this document')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.application')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.documentslot', verbose_name='Document Slot')),
            ],
            options={
                'verbose_name': 'Application Document',
                'verbose_name_plural': 'Application Documents',
                'ordering': ['slot__order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Verification Token',
                'verbose_name_plural': 'Email Verification Tokens',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10)),
                ('subject', models.CharField(max_length=300)),
                ('body_preview', models.TextField(blank=True, help_text='First 500 chars of message body')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('queued', 'Queued')], default='queued', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='admissions.application')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('other_names', models.CharField(blank=True, max_length=100, verbose_name='Other Names')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other / Prefer not to say')], max_length=10, verbose_name='Gender')),
                ('nationality', models.CharField(default='Ugandan', max_length=100, verbose_name='Nationality')),
                ('district_of_origin', models.CharField(blank=True, max_length=100, verbose_name='District of Origin')),
                ('religion', models.CharField(blank=True, max_length=100, verbose_name='Religion')),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='admissions/passport_photos/', verbose_name='Passport Photo')),
                ('has_special_needs', models.BooleanField(default=False, verbose_name='Has Special Needs / Disabilities')),
                ('special_needs_details', models.TextField(blank=True, verbose_name='Special Needs Details')),
                ('medical_conditions', models.TextField(blank=True, verbose_name='Medical Conditions')),
                ('blood_group', models.CharField(blank=True, max_length=10, verbose_name='Blood Group')),
                ('guardian_name', models.CharField(max_length=200, verbose_name='Guardian Full Name')),
                ('guardian_relationship', models.CharField(help_text='e.g. Father, Mother, Uncle, Legal Guardian', max_length=50, verbose_name='Relationship to Student')),
                ('guardian_phone', models.CharField(max_length=20, verbose_name='Guardian Phone Number')),
                ('guardian_email', models.EmailField(blank=True, max_length=254, verbose_name='Guardian Email')),
                ('guardian_occupation', models.CharField(blank=True, max_length=200, verbose_name='Guardian Occupation')),
                ('guardian_address', models.TextField(blank=True, verbose_name='Guardian Address')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, verbose_name='Emergency Contact Name')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Emergency Contact Phone')),
                ('cocurricular_interests', models.TextField(blank=True, verbose_name='Co-curricular Interests')),
                ('previous_school_name', models.CharField(blank=True, max_length=300, verbose_name='Previous School Name')),
                ('previous_school_district', models.CharField(blank=True, max_length=100, verbose_name='Previous School District')),
                ('last_class_attended', models.CharField(blank=True, max_length=100, verbose_name='Last Class Attended')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='admissions.applicantaccount', verbose_name='Account Holder')),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='admissions.studentprofile', verbose_name='Student'),
        ),
    ]
